version: "3.9"
name: web-bang-hang-dhkhtn
services:
  mysql_db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql #attention here
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_db:/var/lib/mysql
      - ./sql/qlbh.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  # webbanhang:
  #   image: webbanhang
  #   build:
  #     dockerfile: Dockerfile
  #     context: "."
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
volumes:
  mysql_db:
    driver: local
